services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      target: dev
    working_dir: /husen
    volumes:
      - type: bind
        source: ./
        target: /husen
      # - type: bind
      #   source: /tmp/.X11-unix
      #   target: /tmp/.X11-unix
    ports:
      - '127.0.0.1:5173:5173'
    environment:
      LANG: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
    tty: true
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: husendb
    ports:
      - '5432:5432'
    volumes:
      - husen_data:/var/lib/postgresql/data

volumes:
  husen_data:
